"""message_originalprompt_field_changed

Revision ID: 1afa28d2c420
Revises: 95259d6826a7
Create Date: 2023-08-03 11:37:43.615655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1afa28d2c420"
down_revision = "95259d6826a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER DATABASE chatbot REFRESH COLLATION VERSION")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("original_prompt", sa.String(), nullable=True))
    op.drop_column("message", "originalPrompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("originalPrompt", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("message", "original_prompt")
    # ### end Alembic commands ###
