"""message_model_field_changed

Revision ID: 6378c7f06877
Revises: 4f35398fb96c
Create Date: 2023-08-03 11:33:45.435673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6378c7f06877"
down_revision = "4f35398fb96c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("conversation_id", sa.UUID(), nullable=False))
    op.drop_constraint("message_conversationId_fkey", "message", type_="foreignkey")
    op.create_foreign_key(None, "message", "conversation", ["conversation_id"], ["id"])
    op.drop_column("message", "conversationId")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("conversationId", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_conversationId_fkey",
        "message",
        "conversation",
        ["conversationId"],
        ["id"],
    )
    op.drop_column("message", "conversation_id")
    # ### end Alembic commands ###
