"""message_isAgent_field_changed

Revision ID: 95259d6826a7
Revises: 6378c7f06877
Create Date: 2023-08-03 11:36:44.893982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95259d6826a7"
down_revision = "6378c7f06877"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("is_agent", sa.Boolean(), nullable=False))
    op.drop_column("message", "isAgent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("isAgent", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("message", "is_agent")
    # ### end Alembic commands ###
