version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Postgres.Dockerfile  # Use the custom Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatbot
    ports:
      - '5431:5432'
    volumes:
      - $HOME/chabot/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/001-init.sql    
    networks:
      - application
    container_name: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chatbot
    volumes:
      - ./:/app
    networks:
      - application

volumes:
  data:

networks:
  application:
